"""Lightweight PCB placement and routing."""

from __future__ import annotations

import math
import re
import shutil
import subprocess
from pathlib import Path

from rich.console import Console
from rich.table import Table

from pcbai.core.config import get_settings
from pcbai.models import BillOfMaterials, NetlistDescription, OptimizationMode, PlacementRecord, PlacementResult


def _load_bom_and_nets(schematic_path: Path) -> tuple[BillOfMaterials, NetlistDescription]:
    """Load BOM and netlist companion files generated by the synthesizer."""

    bom_path = schematic_path.with_suffix(".bom.json")
    nets_path = schematic_path.with_suffix(".nets.json")
    if not bom_path.exists():
        references = re.findall(r'\(property "Reference" "([^"]+)"', schematic_path.read_text(encoding="utf-8"))
        items = [
            {
                "reference": reference,
                "value": reference,
                "footprint": "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
                "datasheet_url": "",
                "manufacturer": "Generic",
                "part_number": reference,
                "lcsc_part": "",
                "quantity": 1,
                "unit_price_usd": 0.0,
            }
            for reference in references
        ]
        return BillOfMaterials.model_validate({"items": items}), NetlistDescription(nets=[], signal_flow=[])

    bom = BillOfMaterials.model_validate_json(bom_path.read_text(encoding="utf-8"))
    if nets_path.exists():
        netlist = NetlistDescription.model_validate_json(nets_path.read_text(encoding="utf-8"))
    else:
        netlist = NetlistDescription(nets=[], signal_flow=[])
    return bom, netlist


def _candidate_positions(board_width: float, board_height: float) -> list[tuple[float, float]]:
    """Create a simple grid of candidate placement coordinates."""

    positions: list[tuple[float, float]] = []
    for y in range(15, int(board_height) - 10, 15):
        for x in range(15, int(board_width) - 10, 20):
            positions.append((float(x), float(y)))
    return positions


def _distance(a: tuple[float, float], b: tuple[float, float]) -> float:
    """Return Euclidean distance between two points."""

    return math.dist(a, b)


def _placement_score(
    item_reference: str,
    position: tuple[float, float],
    placed: list[PlacementRecord],
    mode: OptimizationMode,
    board_width: float,
    board_height: float,
) -> float:
    """Score a candidate placement according to the selected optimization mode."""

    x, y = position
    edge_distance = min(x, y, board_width - x, board_height - y)
    density_penalty = 0.0
    signal_bonus = 0.0
    for record in placed:
        separation = _distance((record.x_mm, record.y_mm), position)
        density_penalty += max(0.0, 20.0 - separation)
        if mode == "signal" and item_reference[0] == record.reference[0]:
            signal_bonus += max(0.0, 35.0 - separation)

    thermal_score = (25.0 - edge_distance) if mode == "thermal" and item_reference.startswith(("U", "Q")) else 0.0
    if mode == "thermal" and item_reference.startswith(("R", "C", "J")):
        thermal_score -= edge_distance / 4.0
    if mode == "signal":
        thermal_score = -edge_distance / 8.0
    return thermal_score + signal_bonus - density_penalty


def _place_components(
    bom: BillOfMaterials,
    mode: OptimizationMode,
    board_width: float,
    board_height: float,
) -> list[PlacementRecord]:
    """Place components on a board using a greedy grid search."""

    candidates = _candidate_positions(board_width, board_height)
    placed: list[PlacementRecord] = []
    remaining = sorted(bom.items, key=lambda item: (item.reference[0] not in {"U", "Q"}, item.reference))

    for item in remaining:
        ranked = sorted(
            candidates,
            key=lambda position: _placement_score(item.reference, position, placed, mode, board_width, board_height),
            reverse=True,
        )
        best = ranked[0]
        candidates.remove(best)
        score = _placement_score(item.reference, best, placed, mode, board_width, board_height)
        placed.append(
            PlacementRecord(
                reference=item.reference,
                footprint=item.footprint,
                x_mm=best[0],
                y_mm=best[1],
                rotation_deg=0.0,
                score=score,
            )
        )
    return placed


def _pad_geometry(reference: str) -> list[tuple[str, float, float, float, float]]:
    """Return simple local pad geometry for generated footprints."""

    if reference.startswith(("R", "C", "D")):
        return [("1", -0.8, 0.0, 0.9, 1.0), ("2", 0.8, 0.0, 0.9, 1.0)]
    if reference.startswith("J"):
        return [("1", -1.27, 0.0, 1.2, 1.2), ("2", 1.27, 0.0, 1.2, 1.2)]
    return [
        ("1", -2.2, 1.9, 0.6, 1.5),
        ("2", -0.7, 1.9, 0.6, 1.5),
        ("3", 0.7, 1.9, 0.6, 1.5),
        ("4", 2.2, 1.9, 0.6, 1.5),
        ("5", 2.2, -1.9, 0.6, 1.5),
        ("6", 0.7, -1.9, 0.6, 1.5),
        ("7", -0.7, -1.9, 0.6, 1.5),
        ("8", -2.2, -1.9, 0.6, 1.5),
    ]


def _build_board_text(
    bom: BillOfMaterials,
    netlist: NetlistDescription,
    placement_result: PlacementResult,
) -> str:
    """Generate a minimal KiCad PCB file."""

    net_names = [""] + [net.net_name for net in netlist.nets]
    net_index = {name: index for index, name in enumerate(net_names)}
    lines = [
        '(kicad_pcb (version 20221018) (generator pcbai)',
        '  (general (thickness 1.6))',
        '  (paper "A4")',
        '  (layers',
        '    (0 "F.Cu" signal)',
        '    (31 "B.Cu" signal)',
        '    (36 "B.SilkS" user)',
        '    (37 "F.SilkS" user)',
        '    (38 "B.Mask" user)',
        '    (39 "F.Mask" user)',
        '    (44 "Edge.Cuts" user)',
        '    (47 "F.CrtYd" user)',
        '  )',
        f'  (gr_rect (start 0 0) (end {placement_result.board_width_mm:.2f} {placement_result.board_height_mm:.2f}) (stroke (width 0.1) (type default)) (fill none) (layer "Edge.Cuts"))',
    ]

    for index, name in enumerate(net_names[1:], start=1):
        lines.append(f'  (net {index} "{name}")')

    bom_by_ref = {item.reference: item for item in bom.items}
    pin_to_net: dict[tuple[str, str], str] = {}
    for net in netlist.nets:
        for pin in net.pins:
            pin_to_net[(pin.reference, pin.pin_number)] = net.net_name

    for placement in placement_result.placements:
        item = bom_by_ref[placement.reference]
        lines.extend(
            [
                f'  (footprint "{item.footprint}" (layer "F.Cu")',
                f'    (at {placement.x_mm:.2f} {placement.y_mm:.2f} {placement.rotation_deg:.2f})',
                f'    (property "Reference" "{item.reference}" (at 0 -3 0) (layer "F.SilkS"))',
                f'    (property "Value" "{item.value}" (at 0 3 0) (layer "F.Fab"))',
                '    (attr smd)',
                '    (fp_line (start -3 -2.5) (end 3 -2.5) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))',
                '    (fp_line (start -3 2.5) (end 3 2.5) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))',
                '    (fp_line (start -3.5 -2.8) (end 3.5 -2.8) (stroke (width 0.05) (type solid)) (layer "F.CrtYd"))',
                '    (fp_line (start 3.5 -2.8) (end 3.5 2.8) (stroke (width 0.05) (type solid)) (layer "F.CrtYd"))',
                '    (fp_line (start 3.5 2.8) (end -3.5 2.8) (stroke (width 0.05) (type solid)) (layer "F.CrtYd"))',
                '    (fp_line (start -3.5 2.8) (end -3.5 -2.8) (stroke (width 0.05) (type solid)) (layer "F.CrtYd"))',
            ]
        )
        for pad_number, x, y, width, height in _pad_geometry(item.reference):
            net_name = pin_to_net.get((item.reference, pad_number), "")
            net_id = net_index.get(net_name, 0)
            net_clause = f' (net {net_id} "{net_name}")' if net_id else ""
            lines.append(
                f'    (pad "{pad_number}" smd rect (at {x:.2f} {y:.2f}) (size {width:.2f} {height:.2f}) (layers "F.Cu" "F.Paste" "F.Mask"){net_clause})'
            )
        lines.append("  )")

    for net_id, net in enumerate(netlist.nets, start=1):
        if len(net.pins) < 2:
            continue
        first_pin = next((placement for placement in placement_result.placements if placement.reference == net.pins[0].reference), None)
        if not first_pin:
            continue
        for peer in net.pins[1:]:
            second_pin = next((placement for placement in placement_result.placements if placement.reference == peer.reference), None)
            if not second_pin:
                continue
            lines.append(
                f'  (segment (start {first_pin.x_mm:.2f} {first_pin.y_mm:.2f}) (end {second_pin.x_mm:.2f} {second_pin.y_mm:.2f}) (width 0.25) (layer "F.Cu") (net {net_id}))'
            )
            lines.append(
                f'  (via (at {(first_pin.x_mm + second_pin.x_mm) / 2:.2f} {(first_pin.y_mm + second_pin.y_mm) / 2:.2f}) (size 0.60) (drill 0.30) (layers "F.Cu" "B.Cu") (net {net_id}))'
            )

    lines.append(")")
    return "\n".join(lines) + "\n"


def _try_freerouting(pcb_path: Path) -> bool:
    """Attempt freerouting if a jar is available nearby."""

    jar_path = shutil.which("freerouting.jar")
    if not jar_path:
        for candidate in [Path("freerouting.jar"), Path("tools/freerouting.jar")]:
            if candidate.exists():
                jar_path = str(candidate)
                break
    if not jar_path:
        return False
    try:
        subprocess.run(["java", "-jar", jar_path, "-de", str(pcb_path)], check=False, capture_output=True, text=True, timeout=60)
    except Exception:
        return False
    return True


def _render_placement_table(result: PlacementResult, console: Console) -> None:
    """Display placement results in the terminal."""

    table = Table(title=f"Placement Summary ({result.optimization_mode})")
    table.add_column("Ref")
    table.add_column("Footprint")
    table.add_column("X (mm)", justify="right")
    table.add_column("Y (mm)", justify="right")
    table.add_column("Score", justify="right")
    for placement in result.placements:
        table.add_row(
            placement.reference,
            placement.footprint,
            f"{placement.x_mm:.2f}",
            f"{placement.y_mm:.2f}",
            f"{placement.score:.2f}",
        )
    console.print(table)


def route_pcb(
    schematic_path: str | Path,
    optimization_mode: OptimizationMode = "default",
    output_dir: str | Path | None = None,
    console: Console | None = None,
) -> str:
    """Generate a minimally routed KiCad PCB from a schematic."""

    console = console or Console()
    schematic_file = Path(schematic_path)
    root_dir = Path(output_dir) if output_dir else get_settings().ensure_output_dir()
    root_dir.mkdir(parents=True, exist_ok=True)
    pcb_path = root_dir / f"{schematic_file.stem}.kicad_pcb"

    bom, netlist = _load_bom_and_nets(schematic_file)
    board_width, board_height = 100.0, 80.0
    placements = _place_components(bom, optimization_mode, board_width, board_height)
    result = PlacementResult(
        optimization_mode=optimization_mode,
        board_width_mm=board_width,
        board_height_mm=board_height,
        placements=placements,
        nets_routed=len(netlist.nets),
        freerouting_used=False,
    )
    pcb_path.write_text(_build_board_text(bom, netlist, result), encoding="utf-8")
    result.freerouting_used = _try_freerouting(pcb_path)
    pcb_path.with_suffix(".placement.json").write_text(result.model_dump_json(indent=2), encoding="utf-8")
    _render_placement_table(result, console)
    console.print(
        "[yellow]Freerouting not found; board remains minimally routed.[/yellow]"
        if not result.freerouting_used
        else "[green]Freerouting executed.[/green]"
    )
    return str(pcb_path)
